[package]
name = "cryptopals"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
encoding_rs = "0.8.35"
getrandom = "0.3.3"
hamming = "0.1.3"
hex = "0.4.3"
itertools = "0.14.0"
rand = "0.9.2"
